// ADD NEW
export const ADD_NEW_PASSWORD_START = "ADD_NEW_PASSWORD_START";
export const ADD_NEW_PASSWORD_SUCCESS = "ADD_NEW_PASSWORD_SUCCESS";
export const ADD_NEW_PASSWORD_ERROR = "ADD_NEW_PASSWORD_ERROR";
// FETCH DATA
export const FETCH_LIST_PASSWORD_START = "FETCH_LIST_PASSWORD_START";
export const FETCH_LIST_PASSWORD_SUCCESS = "FETCH_LIST_PASSWORD_SUCCESS";
export const FETCH_LIST_PASSWORD_ERROR = "FETCH_LIST_PASSWORD_ERROR";
// DELETE DATA
export const DELETE_LIST_PASSWORD_START = "DELETE_LIST_PASSWORD_START";
export const DELETE_LIST_PASSWORD_SUCCESS = "DELETE_LIST_PASSWORD_SUCCESS";
export const DELETE_LIST_PASSWORD_ERROR = "DELETE_LIST_PASSWORD_ERROR";
// UPDATE DATA
export const UPDATE_LIST_PASSWORD_START = "UPDATE_LIST_PASSWORD_START";
export const UPDATE_LIST_PASSWORD_SUCCESS = "UPDATE_LIST_PASSWORD_SUCCESS";
export const UPDATE_LIST_PASSWORD_ERROR = "UPDATE_LIST_PASSWORD_ERROR";
